locale = "pt-BR"
label = "Português (Brasil)"
direction = "ltr"
weight = 1

title = "Labmaker de Ramon"
copyright = "&copy; 2026 Ramon Vieira Souza"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Página para projetos pessoais."

[params.author]
  name = "Ramon Vieira Souza"
  image = "img/author.jpg"
  headline = "Sua frase de efeito aqui!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { github = "https://github.com/ramonvsbr" },
    { linkedin = "https://linkedin.com/in/ramonvsouza" },
  ]
